import IOSurface
import SwiftUI
import UIKit

// Task 16 motion references: `-renderer swiftui -motion <id>` renders an entry
// of `assets/motion.json` (generated by tool/scenes/gen_motion.py).

struct MotionShape: Decodable {
  let x, y, w, h, radius: Double
  let shape, variant: String
  let tint: String?
  let glassId: String?
}

struct MotionPoint: Decodable { let x, y: Double }

struct MotionSpec: Decodable {
  let id, kind, background, brightness: String
  let spacing: Double?
  let shape: MotionShape?
  let before, after: [MotionShape]?
  let touch: MotionPoint
}

struct MotionFile: Decodable { let motion: [MotionSpec] }

enum MotionScenes {
  /// Handles `-motion <id>` for the SwiftUI renderer. Returns false when the
  /// launch is not a SwiftUI motion launch (the static host then runs).
  static func install(in window: UIWindow?) -> Bool {
    // `-dump` (Task 16b) captures the screen, so it serves both renderers.
    if LaunchArgs.arg("motion") != nil, let d = LaunchArgs.arg("dump") {
      FrameDump.shared = FrameDump(spec: d)
    }
    guard let id = LaunchArgs.arg("motion"), LaunchArgs.arg("renderer") == "swiftui",
          let window else { return false }
    guard #available(iOS 26.0, *) else {
      fail(window, "SwiftUI motion reference needs iOS 26 or later")
      return true
    }
    guard let p = ReferenceAssets.path("assets/motion.json"),
          let data = FileManager.default.contents(atPath: p),
          let file = try? JSONDecoder().decode(MotionFile.self, from: data),
          let spec = file.motion.first(where: { $0.id == id }) else {
      fail(window, "motion not found: \(id)")
      return true
    }
    guard let bg = ReferenceAssets.image(spec.background) else {
      fail(window, "background missing: \(spec.background)")
      return true
    }
    window.rootViewController = UIHostingController(
      rootView: MotionSceneView(spec: spec, background: bg))
    return true
  }

  private static func fail(_ window: UIWindow, _ message: String) {
    NSLog("MotionScenes: %@", message)
    let vc = UIViewController()
    vc.view.backgroundColor = .magenta
    let label = UILabel(frame: vc.view.bounds.insetBy(dx: 16, dy: 0))
    label.text = "MOTION FAILED: \(message)"
    label.textColor = .red
    label.backgroundColor = .white
    label.numberOfLines = 0
    label.textAlignment = .center
    label.font = .boldSystemFont(ofSize: 24)
    vc.view.addSubview(label)
    window.rootViewController = vc
  }
}

@available(iOS 26.0, *)
struct MotionSceneView: View {
  let spec: MotionSpec
  let background: UIImage
  @State private var toggled = false
  @Namespace private var namespace

  var body: some View {
    ZStack(alignment: .topLeading) {
      Image(uiImage: background).resizable().interpolation(.none)
        .frame(width: 402, height: 874)
        .onTapGesture {
          guard spec.kind == "morph" else { return }
          // While dumping, the change waits for the next display frame:
          // SwiftUI animates from the transaction's time, so a change at
          // the tap's random point between frames samples the curve at a
          // random sub-frame phase. Flutter's animations start on a frame.
          let toggle = { withAnimation(.bouncy) { toggled.toggle() } }
          if let dump = FrameDump.shared { dump.onNextFrame(toggle) } else { toggle() }
        }
      if spec.kind == "press", let s = spec.shape {
        glass(s, interactive: true)
      } else {
        GlassEffectContainer(spacing: spec.spacing ?? 0) {
          ZStack(alignment: .topLeading) {
            ForEach((toggled ? spec.after : spec.before) ?? [], id: \.glassId) { s in
              glass(s, interactive: false)
                .glassEffectID(s.glassId ?? "", in: namespace)
            }
          }
          .frame(width: 402, height: 874, alignment: .topLeading)
        }
      }
    }
    .overlay(alignment: .topLeading) { Heartbeat() }
    .frame(width: 402, height: 874, alignment: .topLeading)
    .ignoresSafeArea()
    .environment(\.colorScheme, spec.brightness == "dark" ? .dark : .light)
    .statusBarHidden(true)
  }

  private func glass(_ s: MotionShape, interactive: Bool) -> some View {
    var g: Glass = s.variant == "clear" ? .clear : .regular
    if let t = s.tint { g = g.tint(Color(rgbaHex: t)) }
    if interactive { g = g.interactive() }
    let outline: AnyShape = switch s.shape {
    case "capsule": AnyShape(Capsule())
    case "circle": AnyShape(Circle())
    default: AnyShape(RoundedRectangle(cornerRadius: s.radius, style: .continuous))
    }
    // An empty `Color.clear` gets no interactive response (measured: the
    // press leaves every pixel unchanged); near-zero alpha content does, and
    // still rounds to nothing (the resting frame matches the static
    // reference capture pixel for pixel).
    return Color.white.opacity(interactive ? 0.001 : 0)
      .frame(width: s.w, height: s.h)
      .glassEffect(g, in: outline)
      .position(x: s.x + s.w / 2, y: s.y + s.h / 2)
  }
}

/// A 2 pt square at the top-left corner that changes every display frame.
/// It keeps the simulator's recorder (which writes a frame only when the
/// screen changes) from idling before the touch: after an idle gap it
/// delivers a backlog of frames with compressed timestamps, which distorts
/// the measured spring. It lies outside every motion crop. The Flutter
/// motion view draws the same square.
@available(iOS 26.0, *)
struct Heartbeat: View {
  var body: some View {
    TimelineView(.animation) { context in
      let v = context.date.timeIntervalSinceReferenceDate.truncatingRemainder(dividingBy: 1)
      Rectangle().fill(Color(hue: v, saturation: 1, brightness: 1)).frame(width: 2, height: 2)
    }
  }
}

/// Lossless frame dump (Task 16b): `-dump x,y,w,h,frames` (crop in px).
///
/// On every display frame after `<tmp>/motion-dump/start` appears, the crop
/// of the screen is rendered by the render server into an IOSurface (the
/// same pixels `simctl io screenshot` returns: measured identical within
/// 1/255, glass included) and its `CACurrentMediaTime` is kept. After
/// `frames` frames the PNGs, `meta.json` (`{"renderer", "times", "costs"}`,
/// seconds) and `done` are written to the same folder. It captures the
/// screen, so one path serves both renderers; `tool/fidelity/record_motion.sh`
/// drives it.
///
/// Rejected: `drawHierarchy` renders the glass without its blur (SSIM 0.963
/// against a screenshot); `_UICreateScreenUIImage` is exact but captures
/// the whole screen in about 8 ms on the main thread, which made SwiftUI
/// skip animation frames (SwiftUI against itself down to SSIM 0.92), and it
/// throws off the main thread. This captures only the crop, from a display
/// link on its own thread (no dropped capture frames in 15 takes, measured).
/// Private API; this is a simulator-only test harness.
final class FrameDump: NSObject {
  static var shared: FrameDump?

  #if targetEnvironment(simulator)
  // Private API: compiled into simulator builds only.
  private typealias RenderDisplayFn = @convention(c) (
    UInt32, CFString, IOSurfaceRef, Int32, Int32
  ) -> Void
  private static let renderDisplay: RenderDisplayFn? = {
    guard let sym = dlsym(UnsafeMutableRawPointer(bitPattern: -2), "CARenderServerRenderDisplay")
    else { return nil }
    return unsafeBitCast(sym, to: RenderDisplayFn.self)
  }()
  private static let displayName: String =
    ((UIScreen.main.value(forKey: "_display") as? NSObject)?.value(forKey: "name") as? String)
    ?? "LCD"
  #endif

  private let crop: CGRect
  private let count: Int
  private let dir = URL(fileURLWithPath: NSTemporaryDirectory())
    .appendingPathComponent("motion-dump")
  // Capture thread only.
  private var times: [Double] = []
  private var costs: [Double] = []  // capture time per frame, s
  private var images: [CGImage] = []
  private var armed = false
  // Main thread only.
  private var pending: [() -> Void] = []

  init(spec: String) {
    let v = spec.split(separator: ",").compactMap { Double($0) }
    crop = v.count >= 4 ? CGRect(x: v[0], y: v[1], width: v[2], height: v[3]) : .zero
    count = v.count >= 5 ? Int(v[4]) : 180
    super.init()
    #if targetEnvironment(simulator)
    _ = Self.displayName  // UIKit: resolved on the main thread
    #endif
    Self.link(self, #selector(mainTick), .main)
    // The capture waits for the render server (4–9 ms a frame, measured);
    // on the main thread that made the app miss display frames, so it runs
    // on a display link of its own thread.
    let thread = Thread { [unowned self] in
      Self.link(self, #selector(self.tick), .current)
      RunLoop.current.run()
    }
    thread.name = "FrameDump"
    thread.qualityOfService = .userInteractive
    thread.start()
  }

  private static func link(_ target: FrameDump, _ sel: Selector, _ loop: RunLoop) {
    let l = CADisplayLink(target: target, selector: sel)
    l.preferredFrameRateRange = CAFrameRateRange(minimum: 60, maximum: 60, preferred: 60)
    l.add(to: loop, forMode: .common)
  }

  @objc private func mainTick(_ l: CADisplayLink) {
    let actions = pending
    pending = []
    actions.forEach { $0() }
  }

  /// Runs `action` on the main thread at the start of the next display frame.
  func onNextFrame(_ action: @escaping () -> Void) { pending.append(action) }

  /// Capture thread.
  @objc private func tick(_ l: CADisplayLink) {
    if images.count >= count {
      l.invalidate()
      return
    }
    if !armed {
      armed = FileManager.default.fileExists(atPath: dir.appendingPathComponent("start").path)
      if !armed { return }
    }
    let t = CACurrentMediaTime()
    guard let img = renderCrop() else {
      NSLog("FrameDump: render server capture unavailable")
      return
    }
    times.append(t)
    costs.append(CACurrentMediaTime() - t)
    images.append(img)
    if images.count == count {
      let (images, times, costs) = (images, times, costs)
      DispatchQueue.global(qos: .userInitiated).async {
        self.write(images, times, costs)
      }
    }
  }

  private func renderCrop() -> CGImage? {
    #if targetEnvironment(simulator)
    let w = Int(crop.width), h = Int(crop.height)
    guard let fn = Self.renderDisplay,
      let surf = IOSurfaceCreate([
        kIOSurfaceWidth: w, kIOSurfaceHeight: h, kIOSurfaceBytesPerElement: 4,
        kIOSurfacePixelFormat: 0x4247_5241,  // 'BGRA'
      ] as CFDictionary)
    else { return nil }
    // The offset is the crop's origin on the display, in px.
    fn(0, Self.displayName as CFString, surf, Int32(crop.minX), Int32(crop.minY))
    IOSurfaceLock(surf, .readOnly, nil)
    defer { IOSurfaceUnlock(surf, .readOnly, nil) }
    let bpr = IOSurfaceGetBytesPerRow(surf)
    let data = Data(bytes: IOSurfaceGetBaseAddress(surf), count: bpr * h)
    guard let provider = CGDataProvider(data: data as CFData),
      let space = CGColorSpace(name: CGColorSpace.sRGB)
    else { return nil }
    return CGImage(
      width: w, height: h, bitsPerComponent: 8, bitsPerPixel: 32, bytesPerRow: bpr, space: space,
      bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.noneSkipFirst.rawValue
        | CGBitmapInfo.byteOrder32Little.rawValue),
      provider: provider, decode: nil, shouldInterpolate: false, intent: .defaultIntent)
    #else
    return nil  // device builds carry no private API; the dump is simulator-only
    #endif
  }

  private func write(_ images: [CGImage], _ times: [Double], _ costs: [Double]) {
    for (i, img) in images.enumerated() {
      let url = dir.appendingPathComponent(String(format: "%04d.png", i + 1))
      try? UIImage(cgImage: img).pngData()?.write(to: url)
    }
    let meta: [String: Any] = [
      "renderer": LaunchArgs.arg("renderer") ?? "flutter", "times": times, "costs": costs,
    ]
    if let d = try? JSONSerialization.data(withJSONObject: meta) {
      try? d.write(to: dir.appendingPathComponent("meta.json"))
    }
    FileManager.default.createFile(
      atPath: dir.appendingPathComponent("done").path, contents: nil)
  }
}
