import SwiftUI
import UIKit

// Task 16 motion references: `-renderer swiftui -motion <id>` renders an entry
// of `assets/motion.json` (generated by tool/scenes/gen_motion.py).

struct MotionShape: Decodable {
  let x, y, w, h, radius: Double
  let shape, variant: String
  let tint: String?
  let glassId: String?
}

struct MotionPoint: Decodable { let x, y: Double }

struct MotionSpec: Decodable {
  let id, kind, background, brightness: String
  let spacing: Double?
  let shape: MotionShape?
  let before, after: [MotionShape]?
  let touch: MotionPoint
}

struct MotionFile: Decodable { let motion: [MotionSpec] }

enum MotionScenes {
  /// Handles `-motion <id>` for the SwiftUI renderer. Returns false when the
  /// launch is not a SwiftUI motion launch (the static host then runs).
  static func install(in window: UIWindow?) -> Bool {
    guard let id = LaunchArgs.arg("motion"), LaunchArgs.arg("renderer") == "swiftui",
          let window else { return false }
    guard #available(iOS 26.0, *) else {
      fail(window, "SwiftUI motion reference needs iOS 26 or later")
      return true
    }
    guard let p = ReferenceAssets.path("assets/motion.json"),
          let data = FileManager.default.contents(atPath: p),
          let file = try? JSONDecoder().decode(MotionFile.self, from: data),
          let spec = file.motion.first(where: { $0.id == id }) else {
      fail(window, "motion not found: \(id)")
      return true
    }
    guard let bg = ReferenceAssets.image(spec.background) else {
      fail(window, "background missing: \(spec.background)")
      return true
    }
    window.rootViewController = UIHostingController(
      rootView: MotionSceneView(spec: spec, background: bg))
    return true
  }

  private static func fail(_ window: UIWindow, _ message: String) {
    NSLog("MotionScenes: %@", message)
    let vc = UIViewController()
    vc.view.backgroundColor = .magenta
    let label = UILabel(frame: vc.view.bounds.insetBy(dx: 16, dy: 0))
    label.text = "MOTION FAILED: \(message)"
    label.textColor = .red
    label.backgroundColor = .white
    label.numberOfLines = 0
    label.textAlignment = .center
    label.font = .boldSystemFont(ofSize: 24)
    vc.view.addSubview(label)
    window.rootViewController = vc
  }
}

@available(iOS 26.0, *)
struct MotionSceneView: View {
  let spec: MotionSpec
  let background: UIImage
  @State private var toggled = false
  @Namespace private var namespace

  var body: some View {
    ZStack(alignment: .topLeading) {
      Image(uiImage: background).resizable().interpolation(.none)
        .frame(width: 402, height: 874)
        .onTapGesture {
          guard spec.kind == "morph" else { return }
          withAnimation(.bouncy) { toggled.toggle() }
        }
      if spec.kind == "press", let s = spec.shape {
        glass(s, interactive: true)
      } else {
        GlassEffectContainer(spacing: spec.spacing ?? 0) {
          ZStack(alignment: .topLeading) {
            ForEach((toggled ? spec.after : spec.before) ?? [], id: \.glassId) { s in
              glass(s, interactive: false)
                .glassEffectID(s.glassId ?? "", in: namespace)
            }
          }
          .frame(width: 402, height: 874, alignment: .topLeading)
        }
      }
    }
    .overlay(alignment: .topLeading) { Heartbeat() }
    .frame(width: 402, height: 874, alignment: .topLeading)
    .ignoresSafeArea()
    .environment(\.colorScheme, spec.brightness == "dark" ? .dark : .light)
    .statusBarHidden(true)
  }

  private func glass(_ s: MotionShape, interactive: Bool) -> some View {
    var g: Glass = s.variant == "clear" ? .clear : .regular
    if let t = s.tint { g = g.tint(Color(rgbaHex: t)) }
    if interactive { g = g.interactive() }
    let outline: AnyShape = switch s.shape {
    case "capsule": AnyShape(Capsule())
    case "circle": AnyShape(Circle())
    default: AnyShape(RoundedRectangle(cornerRadius: s.radius, style: .continuous))
    }
    // An empty `Color.clear` gets no interactive response (measured: the
    // press leaves every pixel unchanged); near-zero alpha content does, and
    // still rounds to nothing (the resting frame matches the static
    // reference capture pixel for pixel).
    return Color.white.opacity(interactive ? 0.001 : 0)
      .frame(width: s.w, height: s.h)
      .glassEffect(g, in: outline)
      .position(x: s.x + s.w / 2, y: s.y + s.h / 2)
  }
}

/// A 2 pt square at the top-left corner that changes every display frame.
/// It keeps the simulator's recorder (which writes a frame only when the
/// screen changes) from idling before the touch: after an idle gap it
/// delivers a backlog of frames with compressed timestamps, which distorts
/// the measured spring. It lies outside every motion crop. The Flutter
/// motion view draws the same square.
@available(iOS 26.0, *)
struct Heartbeat: View {
  var body: some View {
    TimelineView(.animation) { context in
      let v = context.date.timeIntervalSinceReferenceDate.truncatingRemainder(dividingBy: 1)
      Rectangle().fill(Color(hue: v, saturation: 1, brightness: 1)).frame(width: 2, height: 2)
    }
  }
}
